### PR TITLE
Remove unecessary compiling flags for go > 1.10

### LINKED ISSUE #26: Running compiled binary on new macOS Monterey 12.0.1 fails
I've found that running the compiled kiya binary in macOS Monterey 12.0.1, with go 1.17.2 is failing with the following error:

```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x1573b72, 0x21)
        /usr/local/go/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff5b8 sp=0x7ff7bfeff598 pc=0x1029531
runtime.goenvs()
        /usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff5e8 sp=0x7ff7bfeff5b8 pc=0x10270b3
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff640 sp=0x7ff7bfeff5e8 pc=0x102bdf4
runtime.rt0_go(0x7ff7bfeff670, 0x3, 0x7ff7bfeff670, 0x1000000, 0x3, 0x7ff7bfeff840, 0x7ff7bfeff845, 0x7ff7bfeff84c, 0x0, 0x7ff7bfeff851, ...)
        /usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff648 sp=0x7ff7bfeff640 pc=0x1051ee4
```

I've checked the script to compile and package the binaries and by removing the setup of `CGO_ENABLED=0` and the flag `-installsuffix cgo` that are only necessary for go versions under 1.10. The flags should be removed with the current go version in the go.mod file (and maybe the go version could be bumped up?).

### PR DESCRIPTION
**Pull request by rokjoana**
Fixes #26

### CODE REVIEW

File: etc/bin/releasegen.sh [hunk 1]
```diff
@@ -31,10 +32,15 @@ for os in Darwin Linux Windows; do
     tar_context_dir="$(dirname "${dir}")"
     tar_dir="kiya"
     mkdir -p "${dir}/bin"
-    CGO_ENABLED=0 GOOS=$(goos "${os}") GOARCH=$(goarch "${arch}") \
+    echo GOOS=$(goos "${os}") GOARCH=$(goarch "${arch}") \
+      go build \
+      -a \
+      -ldflags "-X 'main.version=$(git tag -l --points-at HEAD)'" \
```
Comment (amohabir) [inline etc/bin/releasegen.sh:38]: This one was there to set the version number within the final executable.

**Review by amohabir — APPROVED** [review]

File: go.mod [hunk 2]
```diff
@@ -1,17 +1,30 @@
 module github.com/kramphub/kiya
 
-go 1.14
+go 1.17
```
Comment (emicklei) [inline go.mod:3]: Is this change needed?

Comment (rokjoana) [reply go.mod:3]: not necessary, just a version bump

**Review by emicklei — APPROVED** [review]
